server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.13.57.246:3306/tensquare_qa?characterEncoding=UTF-8
    username: root
    password: zhangxiaopengroot
  jpa: 
    database: MySQL
    show-sql: true
